SeKyun/healthy-miok

- .github/workflows/main.yml
- backend/routes/users.js
test :  1. node pm2 자동 배포 테스트를 위해 script 변경
2. backend/routes/users.js 수정
> test: node pm2

- backend/controllers/greeting_controller.js
스코프에 대한 지식 부족인 것 같다.
sql 안에 sql을 넣어서 변수의 적용 범위가 다음 sql 까지 되도록 고쳤다.
(맞는 이해인지 잘 모르겠음.)
> fix: [db] greeting table에서 데이터가 가지않는 오류

- backend/app.js
- backend/config/key.js
- backend/config/prod.js
- backend/package-lock.json
- backend/package.json
갑자기 안되는 이유는 모르겠지만 ㅜㅜ mysql 설정 변수들을 숨기는건 나중에하기로..
> fix: secrets key 못찾는 에러

- backend/app.js
cors 설정 추가, 라우터를 못찾아갈 때 생기는 에러
> fix: cors 설정

- backend/controllers/blood_sugar_controller.js
> fix: blood_sugar_controller.register

- backend/controllers/blood_sugar_controller.js
> fix: 에러 날수있는  부분들

- backend/controllers/blood_sugar_controller.js
- backend/routes/blood_sugar/index.js
blood_sugar_controller.js에
api요청 쿼리에 today와 when 값을 담아 blood_sugar데이터를 조회하는 기능을 추가
> feat: today와 when으로 blood_sugar 데이터 조회

- backend/controllers/blood_sugar_controller.js
- backend/routes/blood_sugar/index.js
- backend/routes/index.js
> feat: 모든 혈당 불러오기 + today로 정렬

- backend/controllers/blood_sugar_controller.js
- backend/routes/blood_sugar/index.js
요청 데이터
parmas {
startDate: date,
endDate: date,
}
> feat: 혈당 - 특정 기간동안의 데이터 불러오기

- backend/controllers/blood_sugar_controller.js
> fix: sql 고쳤습니다

- backend/controllers/blood_sugar_controller.js
- backend/routes/blood_sugar/index.js
1. date/:today 로 get
2. date/:when 로 get
3. / post --> 새로운 혈당 등록, 이미 있으면 409 에러 전송
> feat: blood-sugar - graph api 업데이트 함. & register 업그레이드 

- backend/controllers/blood_pressure_controller.js
- backend/routes/index.js
- backend/routes/insulin/index.js
> feat: index.js 에 blood_pressure(혈압) api 등록함

- backend/routes/blood_pressure/index.js
- backend/routes/insulin/index.js
> fix: 오류ㅈㅅㅈㅅ

- backend/controllers/blood_pressure_controller.js
> fix: 혈압 api  데이터 가공 후 넘겨주기 시도1

- backend/controllers/blood_pressure_controller.js
- frontend/public/swagger.yaml
localhost --> miok.site로 어디서든지 볼 수 있도록
> feat: swagger 설정 변경

- backend/controllers/blood_sugar_controller.js
- backend/controllers/insulin_controller.js
- backend/controllers/type_insulin_controller.js
- backend/library/status_handler.js
- backend/routes/type_insulin/index.js
- frontend/public/components/schemas/blood-sugar.yaml
- frontend/public/swagger.yaml
1. 인슐린 등록 - 기타 설명 기입 안되는 거 수정
2. 인슐린 타입 - 삭제기능 추가/
3. swagger - swagger 내용 추가추가추가 중
> feat: 인슐린 등록, 인슐린 타입 삭제, swagger

- backend/controllers/insulin_controller.js
insulin 등록시 기타1, 기타2의 내용이 안들어가는것. 실험
> test: 정규식 지웠음.

- backend/controllers/type_insulin_controller.js
- backend/routes/type_insulin/index.js
api 부르기
api/type-insulin/:type
(type 은 'long' 혹은 'short')
> feat: 인슐린 타입 지속성(long) 혹은 속효성(short)만 불러오기

- backend/controllers/insulin_controller.js
- backend/data/db.js
1. post새로 등록할때, 지속성 계속 기입할 수 있는것 막음
2. timzone -9:00로 오는거 변형시킴.
> feat: insulin api

- backend/controllers/blood_pressure_controller.js
- backend/controllers/blood_sugar_controller.js
- backend/routes/blood_pressure/index.js
> feat: 혈당 그래프 api, 혈압 그래프 api

- backend/controllers/insulin_controller.js
- backend/routes/insulin/index.js
사용방법
1. post로 불러야함.
2. api/insulin/graph
3. body에 dates, cnt 넣어야함. (dates는 날짜들 있는 배열, cnt는 날짜가 몇개 있는지)
> feat: insulin 그래프 api

- backend/controllers/insulin_controller.js
> test: 인슐린 graph api 시도 2
